### ISSUE TITLE
Stupid QQ下还能抓到图片吗？

### ISSUE THREAD

**Issue by nicholascw** [younfor/PyLinuxQQ#3]
同学聊天一向不说话全靠表情包。Stupid QQ登录不是要QRCode？可以帐号密码吗？可以就考虑凑活着用

**Comment by younfor** [comment]
能，不过协议你得重新搞了

发自 网易邮箱大师
在2016年04月05日 13:38，Nicholas Wang 写道:

同学聊天一向不说话全靠表情包。Stupid QQ登录不是要QRCode？可以帐号密码吗？可以就考虑凑活着用
